<?php
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$value = $block->getData('form_value');
$name = $block->getData('form_name');
$id = $block->getData('form_id');
?>
<input class="js_color_widget_config"
       name="<?= $escaper->escapeHtmlAttr($name) ?>" 
       value="<?= $escaper->escapeHtmlAttr($value) ?>"
       id="<?= $escaper->escapeHtmlAttr($id) ?>" />
<div class="img_uploader_block">
    <img id="img_uploaded_preview" src="" width="200" style="max-width:200px;" />
    <input id="upload_image" name="image" type="file"/>
</div>

<div class="color_widget js-color-widget">
    <div class="panel">
        <button class="js-add-button">+</button>
    </div>
    <div class="preview js_color_widget">

    </div>
</div>


<script>
    (function(){
        
        let widgetPreview = document.querySelectorAll(".js-color-widget");
        let imageUpload = document.querySelector("#upload_image");

        if (!widgetPreview.length || !FORM_KEY) {
            return;
        }

        function createWidgetPreview(element){
            let addButtons = element.querySelector('.js-add-button');
            let imgInput = document.getElementById("<?= $escaper->escapeHtmlAttr($id) ?>");
            let loadedData = imgInput.value+'';

            function implementImagePreview(imgSrc) {
                let imgElement = document.getElementById("img_uploaded_preview");
                imgElement.src = imgSrc;
            }

            if (loadedData) {
                loadedData = JSON.parse(loadedData);
                if (loadedData.image_url) {
                    implementImagePreview(loadedData.image_url);
                }
            }

            addButtons.addEventListener('click', function(event){
                event.preventDefault();

                let formData = new FormData();
                formData.append('test_value', 'Hello from frontend')
                formData.append('form_key', FORM_KEY);
                console.log(imageUpload.files[0]);
                if (imageUpload && imageUpload.files[0]) {
                    formData.append('filepath', imageUpload.files[0]);
                }
                
                fetch(
                    '/admin/postimage/index/upload',
                    {
                        method: 'POST',
                        credentials: "same-origin",
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest'
                        },
                        body: formData
                    }
                ).then( response => {
                    console.log(response);
                    return response.json();
                })
                .then(data => {
                    /* TODO: Fix this part */
                    console.log(data);
                    
                    implementImagePreview(data.image_url);

                    let saveObj = {};
                    saveObj.image_url = data.image_url;
                    imgInput.value = JSON.stringify(saveObj);
                    /* END TODO */
                });

            });
        }

        widgetPreview.forEach(createWidgetPreview);

    })();
</script>


<style>
.img_uploader_block {
    display:flex;
    flex-direction:column;
    gap:4px;
}
.admin__field.field.field-<?= $escaper->escapeCss($id) ?> {
    display: flex;
    flex-direction: column;
}
.admin__field.field.field-<?= $escaper->escapeCss($id) ?> .admin__field,
.admin__field.field.field-<?= $escaper->escapeCss($id) ?> .admin__field-control.control {
    width: 100%;
}
.admin__field.field.field-<?= $escaper->escapeCss($id) ?> .label.admin__field-label {
    text-align: left;
}

.js_color_widget_config {
    display:none;
}
.color_widget {
    border: 1px solid #333;
}
.color_widget .panel {
    background-color: #eee;
    padding: 4px;
}
.color_widget .preview {
    min-height:30px;
}
</style>

