<?php

/**
  *  Copyright Dmitry Hrynchyk
*/

declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */

$value = $block->getData('form_value');
$name = $block->getData('form_name');
$id = $block->getData('form_id');
?>
<div>
    <input value="<?= $escaper->escapeHtmlAttr($value) ?>"/>
    <input value="<?= $escaper->escapeHtmlAttr($name) ?>"/>
    <input value="<?= $escaper->escapeHtmlAttr($id) ?>"/>
</div>